import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {transform,hourFields,hourlyProbability,probabilityWindow,condition,dayKey,VERSION} from '../mapper.mjs';
import {Weather,WeatherKit2,ByteBuffer,ConditionCode} from '../vendor/weatherkit-codec.full.mjs';
const info=JSON.parse(fs.readFileSync(new URL('../research/actual-brief.json',import.meta.url)));
const original=new Uint8Array(fs.readFileSync(new URL(`../research/apple-${info.source.id}.bin`,import.meta.url)));
const now=Math.floor(info.source.time),h=Math.floor(now/3600)*3600;
const base={source:'CWA',location:{stationId:'TEST'},current:{temperature:21.2,humidity:0.73,windSpeed:7.2,windDirection:135,observationTime:now-600},shortTerm:{points:[{forecastStart:h,temperature:20,temperatureApparent:22,dewPoint:17,humidity:.7,windSpeed:7.2},{forecastStart:h+10800,temperature:26,temperatureApparent:28,dewPoint:20,humidity:.85,windSpeed:10.8}],intervals:[{start:h,end:h+10800,weatherText:'陰短暫陣雨',precipitationChance:.7}]},weekly:{points:[],intervals:[]}};
const root=b=>Weather.getRootAsWeather(new ByteBuffer(b));
const approx=(a,b)=>assert.ok(Math.abs(a-b)<0.0001,`${a} != ${b}`);
test('version is release 0.3.1',()=>assert.equal(VERSION,'0.3.1'));
test('current CWA observations and forecast estimates use correct units',()=>{const {bytes,report}=transform(original,base,now),c=root(bytes).currentWeather();approx(c.temperature(),21.2);assert.equal(c.humidity(),73);approx(c.windSpeed(),7.2);assert.equal(c.windDirection(),135);assert.equal(c.asOf(),now-600);assert.equal(c.conditionCode(),ConditionCode.RAIN);assert.ok(report.coverage.currentFields>=5);approx(c.temperatureApparent(),22+(now-h)/1800);});
test('hourly points interpolate each numeric field independently',()=>{const p=[{forecastStart:h,temperature:20,windSpeed:3},{forecastStart:h+3600,temperature:21},{forecastStart:h+10800,temperature:23,windSpeed:9}];const v=hourFields(p,h+3600);assert.equal(v.temperature,21);assert.equal(v.windSpeed,5);assert.match(v._sources.windSpeed,/interpolation/);});
test('forecast never extrapolates and gaps >3h stay Apple',()=>{assert.equal(hourFields(base.shortTerm.points,h-1).temperature,undefined);assert.equal(hourFields(base.shortTerm.points,h+10801).temperature,undefined);assert.equal(hourFields([{forecastStart:h,temperature:10},{forecastStart:h+14400,temperature:20}],h+3600).temperature,undefined);});
test('3h PoP is split to aggregate-preserving hourly PoP',()=>{const p=hourlyProbability(base.shortTerm.intervals,h);approx(p.value,1-Math.pow(.3,1/3));const a=root(transform(original,base,now).bytes).forecastHourly();let checked=0;for(let i=0;i<a.hoursLength();i++){const x=a.hours(i);if(x.forecastStart()>=h&&x.forecastStart()<h+10800){assert.equal(x.precipitationChance(),Math.round(p.value*100));checked++;}}assert.ok(checked>0);});
test('exact and interpolated forecast values arrive in actual FlatBuffer',()=>{const a=root(transform(original,base,now).bytes).forecastHourly();let checked=0;for(let i=0;i<a.hoursLength();i++){let t=a.hours(i);if(t.forecastStart()===h+3600){approx(t.temperature(),22);approx(t.windSpeed(),8.4);checked++;}}assert.equal(checked,1);});
test('unsupported roots, pressure, radar values stay unchanged',()=>{const bytes=transform(original,base,now).bytes;for(const k of ['airQuality','locationInfo','weatherAlerts','forecastNextHour'])assert.deepEqual(WeatherKit2.decode(new ByteBuffer(bytes),[k]),WeatherKit2.decode(new ByteBuffer(original),[k]));for(const k of ['pressure','visibility','precipitationIntensity','windGust'])assert.equal(root(bytes).currentWeather()[k](),root(original).currentWeather()[k]());});
test('all writes are contained in reported scalar bytes',()=>{const {bytes,report}=transform(original,base,now);assert.equal(bytes.length,original.length);const allowed=new Set(report.changes.flatMap(c=>Array.from({length:c.size},(_,i)=>c.offset+i)));for(let i=0;i<bytes.length;i++)if(bytes[i]!==original[i])assert.ok(allowed.has(i));});
test('complete consecutive day/night CWA extrema and period audit',()=>{const s=structuredClone(base),d=root(original).forecastDaily().days(2),day=d.forecastStart(),start=day+21600;s.weekly.intervals=[{start,end:start+43200,temperatureMax:32,temperatureMin:24},{start:start+43200,end:start+86400,temperatureMax:27,temperatureMin:22}];const result=transform(original,s,now),after=root(result.bytes).forecastDaily().days(2);assert.equal(after.temperatureMax(),32);assert.equal(after.temperatureMin(),22);assert.equal(result.report.dailyPeriods[0].start,start);assert.equal(result.report.dailyPeriods[0].appleStart,day);});
test('partial or non-contiguous day/night extrema retain Apple values',()=>{const s=structuredClone(base),d=root(original).forecastDaily().days(2),start=d.forecastStart()+21600;s.weekly.intervals=[{start,end:start+43200,temperatureMax:45,temperatureMin:10}];let a=root(transform(original,s,now).bytes).forecastDaily().days(2);assert.equal(a.temperatureMax(),d.temperatureMax());s.weekly.intervals.push({start:start+40000,end:start+83200,temperatureMax:45,temperatureMin:10});a=root(transform(original,s,now).bytes).forecastDaily().days(2);assert.equal(a.temperatureMax(),d.temperatureMax());});
test('omitted scalar is inserted and readable by native getter',()=>{const b=Uint8Array.from(original),c=root(b).currentWeather(),v=new DataView(b.buffer),vt=c.bb_pos-v.getInt32(c.bb_pos,true);v.setUint16(vt+78,0,true);const {bytes,report}=transform(b,base,now);assert.ok(report.changes.some(s=>s.field==='current.windDirection'&&s.inserted));assert.equal(root(bytes).currentWeather().windDirection(),135);assert.equal(report.skippedFields,0);});
test('future/outdated/NaN timestamps and malformed bodies rejected',()=>{for(const ts of [now-6000,now+600,NaN])assert.throws(()=>transform(original,{...base,current:{...base.current,observationTime:ts}},now));assert.throws(()=>transform(new Uint8Array(3),base,now));const b=Uint8Array.from(original);new DataView(b.buffer).setUint32(0,0x7fffffff,true);assert.throws(()=>transform(b,base,now));});
test('condition mapping handles unknown, mixed precipitation and clouds',()=>{assert.equal(condition('晴'),ConditionCode.CLEAR);assert.equal(condition('晴時多雲'),ConditionCode.MOSTLY_CLEAR);assert.equal(condition('多雲時晴'),ConditionCode.PARTLY_CLOUDY);assert.equal(condition('雨夾雪'),ConditionCode.WINTRY_MIX);assert.equal(condition('-99'),undefined);assert.equal(condition('unknown'),undefined);});
test('Taiwan date key includes UTC+8 midnight',()=>assert.equal(dayKey(Date.parse('2026-09-11T16:00:00Z')/1000),'2026-09-12'));

test('CWA pressure, visibility, gust, rain gauge and 1h radar QPF map whenever native scalar is present',()=>{const s=structuredClone(base);s.current.pressure=1008.5;s.current.visibility=13000;s.current.windGust=20;s.current._sources={pressure:'CWA station',visibility:'CWA visibility',windGust:'CWA station'};s.rain={past1h:1.2,past6h:2.3,past24h:3.4,intensity:.6};s.nowcast={start:now,end:now+3600,amount:4.2};const {bytes,report}=transform(original,s,now),c=root(bytes).currentWeather();approx(c.pressure(),1008.5);approx(c.visibility(),13000);approx(c.windGust(),20);approx(c.precipitationAmount24h(),3.4);approx(c.precipitationIntensity(),.6);for(const [field,want,get] of [['precipitationAmount1h',1.2,()=>c.precipitationAmount1h()],['precipitationAmount6h',2.3,()=>c.precipitationAmount6h()],['precipitationAmountNext1h',4.2,()=>c.precipitationAmountNext1h()]]){const skipped=report.skipped.some(x=>x.field==='current.'+field);if(skipped)assert.equal(get(),0);else approx(get(),want);}assert.ok(report.coverage.precipitationFields>=2);});

test('CWA weather alerts rebuild native WeatherKit root while preserving other roots',()=>{const s=structuredClone(base);const t=Math.floor(now);s.requested={latitude:25.09,longitude:121.56};s.weatherAlerts={reportedTime:t,detailsUrl:'https://www.cwa.gov.tw/V8/C/W/Warning.html',attributionUrl:'https://opendata.cwa.gov.tw/',alerts:[{id:'01020304-0506-0708-090a-0b0c0d0e0f10',areaId:'臺北市',areaName:'臺北市',attributionUrl:'https://opendata.cwa.gov.tw/',countryCode:'TW',description:'測試強風特報',token:'test-alert',effectiveTime:t,expireTime:t+3600,issuedTime:t,eventOnsetTime:t,eventEndTime:t+3600,detailsUrl:'https://www.cwa.gov.tw/V8/C/W/Warning.html',phenomenon:'陸上強風',severity:'MODERATE',significance:'ADVISORY',source:'中央氣象署',eventSource:'CWA',urgency:'IMMEDIATE',certainty:'UNKNOWN',importance:'NORMAL',responses:['AVOID'],unknown23:0,unknown24:0,unknown25:0,unknown26:0}]};const before=WeatherKit2.decode(new ByteBuffer(original),['news']).news;const {bytes,report}=transform(original,s,now);assert.notEqual(bytes.length,original.length);assert.equal(report.rebuiltRoots[0].root,'weatherAlerts');const decoded=WeatherKit2.decode(new ByteBuffer(bytes),['weatherAlerts','news']);assert.equal(decoded.weatherAlerts.alerts.length,1);assert.equal(decoded.weatherAlerts.alerts[0].phenomenon,'陸上強風');assert.equal(decoded.weatherAlerts.alerts[0].source,'中央氣象署');assert.deepEqual(decoded.news,before);});

test('probability estimates preserve complete interval survival, endpoints, and coverage gaps',()=>{
 for(const p of [0,.1,.3,.7,.99,1]){
  const rows=[{start:h,end:h+10800,precipitationChance:p}];
  const one=probabilityWindow(rows,h,h+3600),three=probabilityWindow(rows,h,h+10800);
  approx(three.value,p);approx(1-(1-one.value)**3,p);assert.equal(one.estimated,true);
 }
 assert.equal(probabilityWindow([{start:h,end:h+3600,precipitationChance:.5}],h,h+7200).value,undefined);
});
test('current CWA astronomy times are written to calendar-matching native days',()=>{
 const s=structuredClone(base),d=root(original).forecastDaily().days(2),key=dayKey(d.forecastStart());
 s.astronomy={days:[{date:key,sunrise:d.forecastStart()+20000,sunset:d.forecastStart()+64000,moonrise:d.forecastStart()+25000}]};
 const a=root(transform(original,s,now).bytes).forecastDaily().days(2);
 assert.equal(a.sunrise(),d.forecastStart()+20000);assert.equal(a.sunset(),d.forecastStart()+64000);assert.equal(a.moonrise(),d.forecastStart()+25000);
});
test('expansion preserves newer opaque root slot 28 byte-for-byte',()=>{
 const s=structuredClone(base);s.rain={past1h:3.21,past6h:8.65};const result=transform(original,s,now);
 function item(b){const v=new DataView(b.buffer,b.byteOffset,b.byteLength),r=v.getUint32(0,true),vt=r-v.getInt32(r,true),off=v.getUint16(vt+28,true),target=r+off+v.getUint32(r+off,true),tv=target-v.getInt32(target,true),size=v.getUint16(tv+2,true);return b.slice(target,target+size);}
 assert.deepEqual(item(result.bytes),item(original));approx(root(result.bytes).currentWeather().precipitationAmount1h(),3.21);approx(root(result.bytes).currentWeather().precipitationAmount6h(),8.65);
});
test('CWA warning unavailability preserves the Apple warning root',()=>{
 const s=structuredClone(base);s.weatherAlerts=null;
 assert.deepEqual(WeatherKit2.decode(new ByteBuffer(transform(original,s,now).bytes),['weatherAlerts']),WeatherKit2.decode(new ByteBuffer(original),['weatherAlerts']));
});
